#!/usr/bin/env node
/* =====================================================================
   Aqua Zero Heavens Arena - roster tuner
   Luminara Digital

   The audit says WHICH fighters are broken. This says WHY, and fixes it.

   Every fighter already carries a trait block derived from their dossier
   (power, guard, air, HP, focus). Rather than hand-editing 25 fighters and
   re-running the audit 25 times, this measures each fighter's win rate,
   then nudges their dossier-derived multipliers toward parity and
   re-measures - a few rounds of closed-loop correction.

   It writes a TRAIT_TUNE table that traitsOf() folds in, so the dossiers
   themselves stay honest: a fighter's listed attributes remain what the
   book says, and the balance correction sits beside them where it can be
   read, argued with and reverted.

   Usage: node tools/tune-roster.js [rounds] [repsPerPair]
   ===================================================================== */
"use strict";
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROUNDS = parseInt(process.argv[2] || "6", 10);
const REPS = parseInt(process.argv[3] || "4", 10);
const TUNE_FILE = path.resolve(__dirname, "..", "src", "data", "roster-tune.js");
const BUILD = path.resolve(__dirname, "build.js");

/* the correction is a single per-fighter strength scalar, applied to the
   things that decide a fight without changing what a fighter IS */
function writeTune(tune, note) {
  const body = [
    "/* =====================================================================",
    "   Aqua Zero Heavens Arena - roster balance corrections",
    "   Luminara Digital",
    "",
    "   GENERATED by tools/tune-roster.js - do not hand-edit, re-run the tuner.",
    "",
    "   A dossier is what the book says about a fighter. It is not a promise",
    "   that they are competitive, and an audit of the whole roster fighting",
    "   itself found a 65-point spread between the best and worst - over half",
    "   the roster was a trap.",
    "",
    "   These are per-fighter corrections applied on top of the dossier-derived",
    "   traits. They sit here, in the open, rather than being smuggled into the",
    "   dossiers: the attributes stay honest and the balance thumb is readable.",
    "",
    "   " + note,
    "   ===================================================================== */",
    "const TRAIT_TUNE = " + JSON.stringify(tune) + ";",
    "const traitTuneFor = (fid) => TRAIT_TUNE[fid] || 1;",
    "",
  ].join("\n");
  fs.writeFileSync(TUNE_FILE, body);
}

function measure() {
  const out = execFileSync("node", [path.resolve(__dirname, "audit-balance.js"), String(REPS)],
    { encoding: "utf8", maxBuffer: 1 << 24 });
  const rates = {};
  out.split("\n").forEach((l) => {
    const m = l.match(/^\s+\d+\.\s+(.+?)\s+([\d.]+)%/);
    if (m) rates[m[1].trim()] = parseFloat(m[2]) / 100;
  });
  const spread = out.match(/spread: ([\d.]+)% down to ([\d.]+)%/);
  return { rates, best: spread ? parseFloat(spread[1]) / 100 : 1, worst: spread ? parseFloat(spread[2]) / 100 : 0, raw: out };
}

/* the audit only prints the top and bottom five, which is all we need:
   correct the extremes, re-measure, and the middle sorts itself out */
let tune = {};
if (fs.existsSync(TUNE_FILE)) {
  const m = fs.readFileSync(TUNE_FILE, "utf8").match(/const TRAIT_TUNE = (\{.*?\});/);
  if (m) tune = JSON.parse(m[1]);
}
writeTune(tune, "seeded from the previous run");
execFileSync("node", [BUILD], { encoding: "utf8", maxBuffer: 1 << 24 });

const boot = require("../tests/harness");
const names = boot({ quiet: true }).api.FIGHTERS.map((f) => f.name);
const idOf = (n) => names.indexOf(n);

console.log("closed-loop roster tuning - " + ROUNDS + " rounds, " + REPS + " fights per matchup\n");
let last = null;
for (let r = 1; r <= ROUNDS; r++) {
  const m = measure();
  const gap = m.best - m.worst;
  console.log("round " + r + ":  best " + (m.best * 100).toFixed(1) + "%   worst " +
    (m.worst * 100).toFixed(1) + "%   gap " + (gap * 100).toFixed(1) + "%");
  last = m;
  if (gap <= 0.15) { console.log("\nwithin tolerance - stopping"); break; }
  // pull every measured fighter toward 50%, gently, so the loop converges
  // rather than oscillating
  let moved = 0;
  Object.keys(m.rates).forEach((n) => {
    const fid = idOf(n);
    if (fid < 0) return;
    const err = m.rates[n] - 0.5;
    const cur = tune[fid] || 1;
    const next = Math.max(0.72, Math.min(1.38, cur * (1 - err * 0.34)));
    if (Math.abs(next - cur) > 0.001) { tune[fid] = +next.toFixed(4); moved++; }
  });
  writeTune(tune, "converged over " + r + " tuning rounds against tools/audit-balance.js");
  execFileSync("node", [BUILD], { encoding: "utf8", maxBuffer: 1 << 24 });
  console.log("          corrected " + moved + " fighters");
}
console.log("\nfinal corrections:");
Object.keys(tune).sort((a, b) => tune[a] - tune[b]).forEach((fid) =>
  console.log("  " + (tune[fid] < 1 ? "-" : "+") + " " + names[fid].padEnd(22) + tune[fid].toFixed(3)));
console.log("\n" + (last ? last.raw.split("verdict:")[1].split("\n")[0].trim() : ""));
