#!/usr/bin/env node
/* =====================================================================
   Aqua Zero Heavens Arena - roster tuner
   Luminara Digital

   The audit says WHICH fighters are broken. This says WHY, and fixes it.

   Every fighter already carries a trait block derived from their dossier
   (power, guard, air, HP, focus). Rather than hand-editing 25 fighters and
   re-running the audit 25 times, this measures each fighter's win rate,
   then nudges their dossier-derived multipliers toward parity and
   re-measures - a few rounds of closed-loop correction.

   It writes a TRAIT_TUNE table that traitsOf() folds in, so the dossiers
   themselves stay honest: a fighter's listed attributes remain what the
   book says, and the balance correction sits beside them where it can be
   read, argued with and reverted.

   Usage: node tools/tune-roster.js [rounds] [repsPerPair]
   ===================================================================== */
"use strict";
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROUNDS = parseInt(process.argv[2] || "6", 10);
const REPS = parseInt(process.argv[3] || "4", 10);
const TUNE_FILE = path.resolve(__dirname, "..", "src", "data", "roster-tune.js");
const BUILD = path.resolve(__dirname, "build.js");

/* the correction is a single per-fighter strength scalar, applied to the
   things that decide a fight without changing what a fighter IS */
function writeTune(tune, note) {
  const body = [
    "/* =====================================================================",
    "   Aqua Zero Heavens Arena - roster balance corrections",
    "   Luminara Digital",
    "",
    "   GENERATED by tools/tune-roster.js - do not hand-edit, re-run the tuner.",
    "",
    "   A dossier is what the book says about a fighter. It is not a promise",
    "   that they are competitive, and an audit of the whole roster fighting",
    "   itself found a 65-point spread between the best and worst - over half",
    "   the roster was a trap.",
    "",
    "   These are per-fighter corrections applied on top of the dossier-derived",
    "   traits. They sit here, in the open, rather than being smuggled into the",
    "   dossiers: the attributes stay honest and the balance thumb is readable.",
    "",
    "   " + note,
    "   ===================================================================== */",
    "const TRAIT_TUNE = " + JSON.stringify(tune) + ";",
    "const traitTuneFor = (fid) => TRAIT_TUNE[fid] || 1;",
    "",
  ].join("\n");
  fs.writeFileSync(TUNE_FILE, body);
}

function measure() {
  const out = execFileSync("node", [path.resolve(__dirname, "audit-balance.js"), String(REPS)],
    { encoding: "utf8", maxBuffer: 1 << 24 });
  const rates = {};
  out.split("\n").forEach((l) => {
    const m = l.match(/^\s+\d+\.\s+(.+?)\s+([\d.]+)%/);
    if (m) rates[m[1].trim()] = parseFloat(m[2]) / 100;
  });
  const spread = out.match(/spread: ([\d.]+)% down to ([\d.]+)%/);
  return { rates, best: spread ? parseFloat(spread[1]) / 100 : 1, worst: spread ? parseFloat(spread[2]) / 100 : 0, raw: out };
}

/* the audit only prints the top and bottom five, which is all we need:
   correct the extremes, re-measure, and the middle sorts itself out */
let tune = {};
if (fs.existsSync(TUNE_FILE)) {
  const m = fs.readFileSync(TUNE_FILE, "utf8").match(/const TRAIT_TUNE = (\{.*?\});/);
  if (m) tune = JSON.parse(m[1]);
}
writeTune(tune, "seeded from the previous run");
execFileSync("node", [BUILD], { encoding: "utf8", maxBuffer: 1 << 24 });

const boot = require("../tests/harness");
const names = boot({ quiet: true }).api.FIGHTERS.map((f) => f.name);
const idOf = (n) => names.indexOf(n);

/* Correction range. Was 0.72-1.38, and the damage-model collapse walked
   straight into the end of it: five fighters sat pinned at a bound while
   the roster gap held at 48 points, because the loop had run out of thumb.
   A wider range is not a licence to lie about a fighter - the dossier is
   still what it was and the correction is still printed here in the open -
   it is the admission that after the collapse a bad KIT costs more than a
   single strength scalar at 0.72 can buy back.

   The floor then had to go again, 0.62 -> 0.50, for one fighter: Sergio
   Newton, a single-discipline kickboxer with a 26-technique pool and no
   bad options in it, sat at 68.8% while the other twenty-four spanned 8.4
   points. Pinned at 0.62 he was still the best fighter in the game; at
   0.42 he wins 15.6%, so the correction is steep and the answer was
   between the two.

   Worth being exact about what the wider floor did: it let the SEARCH
   move, it is not where the answer sits. The shipped table runs 0.56 to
   1.4214 - no fighter rests on either bound, so neither bound is binding
   and neither is doing the balancing. One fighter needing this much thumb
   is still worth a look at his kit in Phase 3; the table is the record. */
const TUNE_MIN = 0.50, TUNE_MAX = 1.52;
/* 0.34 overshot: rounds 1-3 closed the gap 53 -> 40 and rounds 4-8 opened
   it back to 48, each round chasing the extremes it had created. */
const TUNE_RATE = 0.22;

console.log("closed-loop roster tuning - " + ROUNDS + " rounds, " + REPS + " fights per matchup\n");
let last = null;
/* The loop is noisy - 4 fights per matchup is a coarse measurement and a
   correction can land the wrong side of it. Keeping the best table seen
   rather than the last one means a round that overshoots costs a round,
   not the whole run. */
let bestGap = Infinity, bestTune = JSON.parse(JSON.stringify(tune)), bestRound = 0;
for (let r = 1; r <= ROUNDS; r++) {
  const m = measure();
  const gap = m.best - m.worst;
  console.log("round " + r + ":  best " + (m.best * 100).toFixed(1) + "%   worst " +
    (m.worst * 100).toFixed(1) + "%   gap " + (gap * 100).toFixed(1) + "%");
  last = m;
  if (gap < bestGap) { bestGap = gap; bestTune = JSON.parse(JSON.stringify(tune)); bestRound = r; }
  if (gap <= 0.15) { console.log("\nwithin tolerance - stopping"); break; }
  // pull every measured fighter toward 50%, gently, so the loop converges
  // rather than oscillating
  let moved = 0;
  Object.keys(m.rates).forEach((n) => {
    const fid = idOf(n);
    if (fid < 0) return;
    const err = m.rates[n] - 0.5;
    const cur = tune[fid] || 1;
    const next = Math.max(TUNE_MIN, Math.min(TUNE_MAX, cur * (1 - err * TUNE_RATE)));
    if (Math.abs(next - cur) > 0.001) { tune[fid] = +next.toFixed(4); moved++; }
  });
  writeTune(tune, "converged over " + r + " tuning rounds against tools/audit-balance.js");
  execFileSync("node", [BUILD], { encoding: "utf8", maxBuffer: 1 << 24 });
  console.log("          corrected " + moved + " fighters");
}
if (bestGap < (last ? last.best - last.worst : Infinity)) {
  tune = bestTune;
  /* NOT "converged over N rounds" - it did not converge, the search was
     stopped and the best table it passed through was kept. The file is
     the only record of where a number came from, so it says which. */
  writeTune(tune, "best of " + ROUNDS + " tuning rounds against tools/audit-balance.js" +
    " (round " + bestRound + ", gap " + (bestGap * 100).toFixed(1) + "% - later rounds were worse)");
  execFileSync("node", [BUILD], { encoding: "utf8", maxBuffer: 1 << 24 });
  console.log("\nkept round " + bestRound + " (gap " + (bestGap * 100).toFixed(1) + "%) - later rounds were worse");
}
console.log("\nfinal corrections:");
Object.keys(tune).sort((a, b) => tune[a] - tune[b]).forEach((fid) =>
  console.log("  " + (tune[fid] < 1 ? "-" : "+") + " " + names[fid].padEnd(22) + tune[fid].toFixed(3)));
console.log("\n" + (last ? last.raw.split("verdict:")[1].split("\n")[0].trim() : ""));
